# Generated by Django 3.0.4 on 2020-03-29 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_alternative_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='alternative_identity',
            field=models.CharField(default='defaultalternate', max_length=50),
            preserve_default=False,
        ),
    ]
