# Generated by Django 3.0.4 on 2020-03-29 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20200328_2357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name': 'Creation', 'verbose_name_plural': 'Creations'},
        ),
        migrations.AddField(
            model_name='dish',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='creationvideo'),
        ),
    ]
